# Command to run: docker-compose up

version: '2'

services:
  hello-world-run:
    container_name: hello-world-run
    build: .
    command: go run main.go
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3030:3001"
    environment:
      PORT: 3001